server:
  port: 8081
spring:
  datasource:
    url: ${JDBC_CONNECTION_URL}
    username: ${JDBC_CONNECTION_USERNAME}
    password: ${JDBC_CONNECTION_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
     hibernate:
       type: trace 
