server:
  port: 8081
  servlet:
    context-path: /my-tube-api
spring:
  datasource:
    url: ${JDBC_CONNECTION_URL_MY_TUBE}
    username: ${JDBC_CONNECTION_USERNAME}
    password: ${JDBC_CONNECTION_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
aws:
  s3:
    accessKey: ${AWS_S3_ACCESS_KEY}
    secreteKey: ${AWS_S3_SECRETE_KEY}
    region: ap-south-1
    bucketName: my-tube-assert

assert:
  prefix: assert

logging:
  level:
    org:
      hibernate:
        type: trace
